language: go
go:
 - 1.5
 - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
 - go test -v ./...
 - $HOME/gopath/bin/goveralls -repotoken Kp9xyVcYA2lAmTyYmCzQtH1zmAIymtQxI
